# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install dependencies
      run: |
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
        sudo apt-get update
        sudo apt-get install -y build-essential libhts-dev libboost-dev libcurl4-openssl-dev libcairo2-dev python-numpy python-pandas r-base pandoc

    - name: Install R dependencies
      run: |
        sudo R --vanilla <<EOF
        if(!require(fpc)){install.packages("fpc", repos="https://cloud.r-project.org/")}
        if(!require(ape)){install.packages("ape", repos="https://cloud.r-project.org/")}
        if(!require(getopt)){install.packages("getopt", repos="https://cloud.r-project.org/")}
        if(!require(optparse)){install.packages("optparse", repos="https://cloud.r-project.org/")}
        if(!require(readr)){install.packages("readr", repos="https://cloud.r-project.org/")}
        if(!require(dplyr)){install.packages("dplyr", repos="https://cloud.r-project.org/")}
        if(!require(ggplot2)){install.packages("ggplot2", repos="https://cloud.r-project.org/")}
        if(!require(tidyr)){install.packages("tidyr", repos="https://cloud.r-project.org/")}
        if(!require(gridExtra)){install.packages("gridExtra", repos="https://cloud.r-project.org/")}
        if(!require(lemon)){install.packages("lemon", repos="https://cloud.r-project.org/")}
        if(!require(DT)){install.packages("DT", repos="https://cloud.r-project.org/")}
        if(!require(cluster)){install.packages("cluster", repos="https://cloud.r-project.org/")}
        if(!require(ggrepel)){install.packages("ggrepel", repos="https://cloud.r-project.org/")}
        if(!require(data.table)){install.packages("data.table", repos="https://cloud.r-project.org/")}
        if(!require(kableExtra)){install.packages("kableExtra", repos="https://cloud.r-project.org/")}
        if(!require(rmarkdown)){install.packages("rmarkdown", repos="https://cloud.r-project.org/")}
        if(!require(BiocParallel)){install.packages("BiocParallel", repos="https://cloud.r-project.org/")}
        if(!require(batchtools)){install.packages("batchtools", repos="https://cloud.r-project.org/")}
        if(!require(coin)){install.packages("coin", repos="https://cloud.r-project.org/")}
        if(!require(questionr)){install.packages("questionr", repos="https://cloud.r-project.org/")}
        if(!require(futile.logger)){install.packages("futile.logger", repos="https://cloud.r-project.org/")}
        q()
        EOF
        
    - name: Compile
      run: make 

    # Runs a set of commands using the runners shell
    - name: Check help outputs
      run: |
        python metaSNV.py --help
        python metaSNV_post.py --help
        Rscript metaSNV_subpopr.R --help
        
