# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ca-certificates
        echo 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/' | sudo tee /etc/apt/sources.list.d/r36.list
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
        sudo apt-get update
        sudo apt-get install -y libhts-dev libboost-dev libcurl4-openssl-dev libcairo2-dev python-numpy python-pandas r-base pandoc

    - name: Install R dependencies
      run: |
        sudo R --vanilla <<EOF
        if(!requireNamespace("BiocManager", quietly=TRUE)){install.packages("BiocManager", repos="https://cloud.r-project.org/")}
        if(!requireNamespace("BiocParallel", quietly=TRUE)){BiocManager::install("BiocParallel"); library(BiocParallel)}
        if(!requireNamespace("coin", quietly=TRUE)){install.packages("coin", repos="https://cloud.r-project.org/"); library(coin)}
        if(!requireNamespace("fpc", quietly=TRUE)){install.packages("fpc", repos="https://cloud.r-project.org/"); library(fpc)}
        if(!requireNamespace("ape", quietly=TRUE)){install.packages("ape", repos="https://cloud.r-project.org/"); library(ape)}
        if(!requireNamespace("getopt", quietly=TRUE)){install.packages("getopt", repos="https://cloud.r-project.org/"); library(getopt)}
        if(!requireNamespace("optparse", quietly=TRUE)){install.packages("optparse", repos="https://cloud.r-project.org/"); library(optparse)}
        if(!requireNamespace("readr", quietly=TRUE)){install.packages("readr", repos="https://cloud.r-project.org/"); library(readr)}
        if(!requireNamespace("dplyr", quietly=TRUE)){install.packages("dplyr", repos="https://cloud.r-project.org/"); library(dplyr)}
        if(!requireNamespace("ggplot2", quietly=TRUE)){install.packages("ggplot2", repos="https://cloud.r-project.org/"); library(ggplot2)}
        if(!requireNamespace("tidyr", quietly=TRUE)){install.packages("tidyr", repos="https://cloud.r-project.org/"); library(tidyr)}
        if(!requireNamespace("gridExtra", quietly=TRUE)){install.packages("gridExtra", repos="https://cloud.r-project.org/"); library(gridExtra)}
        if(!requireNamespace("lemon", quietly=TRUE)){install.packages("lemon", repos="https://cloud.r-project.org/"); library(lemon)}
        if(!requireNamespace("DT", quietly=TRUE)){install.packages("DT", repos="https://cloud.r-project.org/"); library(DT)}
        if(!requireNamespace("cluster", quietly=TRUE)){install.packages("cluster", repos="https://cloud.r-project.org/"); library(cluster)}
        if(!requireNamespace("ggrepel", quietly=TRUE)){install.packages("ggrepel", repos="https://cloud.r-project.org/"); library(ggrepel)}
        if(!requireNamespace("data.table", quietly=TRUE)){install.packages("data.table", repos="https://cloud.r-project.org/"); library(data.table)}
        if(!requireNamespace("kableExtra", quietly=TRUE)){install.packages("kableExtra", repos="https://cloud.r-project.org/"); library(kableExtra)}
        if(!requireNamespace("rmarkdown", quietly=TRUE)){install.packages("rmarkdown", repos="https://cloud.r-project.org/"); library(rmarkdown)}
        if(!requireNamespace("batchtools")){install.packages("batchtools", repos="https://cloud.r-project.org/"); library(batchtools)}
        if(!requireNamespace("questionr", quietly=TRUE)){install.packages("questionr", repos="https://cloud.r-project.org/"); library(questionr)}
        if(!requireNamespace("futile.logger", quietly=TRUE)){install.packages("futile.logger", repos="https://cloud.r-project.org/"); library(futile.logger)}
        sessionInfo()
        q()
        EOF
        
    - name: Compile
      run: make 

    # Runs a set of commands using the runners shell
    - name: Check help outputs
      run: |
        python metaSNV.py --help
        python metaSNV_post.py --help
        Rscript metaSNV_subpopr.R --help
        
