# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ca-certificates
        echo 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/' | sudo tee /etc/apt/sources.list.d/r36.list
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
        sudo apt-get update
        sudo apt-get install -y libhts-dev libboost-dev libxml2-dev libssl-dev libcurl4-openssl-dev libcairo2-dev libxt-dev
        sudo apt-get install -y python3-numpy python3-pandas r-base pandoc samtools optipng

    - name: Install R dependencies
      run: |
        sudo R --vanilla <<EOF
        source("src/subpopr/R/installOrLoadPackages.R")
        sessionInfo()
        q()
        EOF

    - name: Compile
      run: make

    # Runs a set of commands using the runners shell
    - name: Check help outputs
      run: |
        python metaSNV.py --help
        python metaSNV_Filtering.py --help
        python metaSNV_DistDiv.py --help
        Rscript metaSNV_subpopr.R --help

    - name: Fetch and unpack test data
      run: |
        wget http://swifter.embl.de/~ralves/metaSNV_test_data/testdata.tar.xz
        tar xvf testdata.tar.xz && rm -f testdata.tar.gz

    - name: Run all of metaSNV with test data
      run: |
        ./metaSNV.py output testdata/all_samples testdata/ref/allReferenceGenomes.fasta
        ./metaSNV_Filtering.py output
        ./metaSNV_DistDiv.py --filt output/filtered/pop --dist
        ./metaSNV_subpopr.R -i output -g testdata/abunds/geneAbundances.tsv -a testdata/abunds/speciesAbundances.tsv
